name: MinecraftLuaScripting
version: '1.0.0'
main: me.touchie771.minecraftLuaScripting.MinecraftLuaScripting
api-version: '1.21'
authors: [ Touchie771 ]
description: A plugin that allows you to run Lua scripts in Minecraft.