name: MinecraftLuaScripting
version: '1.1.2'
main: me.touchie771.minecraftLuaScripting.MinecraftLuaScripting
api-version: '1.18'
authors: [ Touchie771 ]
description: A plugin that allows you to run Lua scripts in Minecraft.
commands:
  luascript:
    description: Manage Lua scripts
    usage: /luascript <reloadall|list|run|reload> [script]
    permission: luascript.admin
permissions:
  luascript.admin:
    description: Allows managing Lua scripts
    default: op